# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27713be08de77040470f98223e7560e9350b99dce9389b63760941f89b8efd28d5a640b0ad692b498098ada24f3af0c87788697fde17e15105b6807ff44a5d7c

test:
  secret_key_base: 48c617500507aa4a150f47467c17703f634303a17184f57597dffa2f56a3b54381f1cdf58c365fc6c23f9245250148c70de710f52067eda864702a34f61e78bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
